version: 0.1

phases:
    build:
        commands: 
            - echo Welcome to the Pipeline
            - wget https://s3-us-west-1.amazonaws.com/mbc-bucket-dependencies-folder/ojdbc7.jar
            - mvn install:install-file -Dfile="ojdbc7.jar" -DgroupId="com.oracle" -DartifactId="ojdbc7" -Dversion="12.1.0" -Dpackaging="jar"
            - mvn clean package 
artifacts:
    files: 
        - target/ERS.war